import React, { Component } from 'react';
import './App.css';
import { SocialIcon } from 'react-social-icons';
import { Link } from 'react-router-dom';



class App extends Component {
  render() {
    return (
      <div className="App">
       <div className="topnav">         
          <Link to="/contact">Contact</Link>
          <Link to="/music">Music</Link>
          <Link to="/coding">Coding</Link>
          <Link to="/aboutMe">About Me</Link>  
          <Link to="/home">Home</Link>         
      </div>
      <div className="main">
        <p> Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5]
Carnatic music, Karnāṭaka saṃgīta or Karnāṭaka saṅgītam is a system of music commonly associated with southern India, including the modern Indian states of Andhra Pradesh, Telangana, Karnataka, Kerala, and Tamil Nadu, as well as Sri Lanka.[1][2] It is one of two main subgenres of Indian classical music that evolved from ancient Hindu traditions, the other subgenre being Hindustani music, which emerged as a distinct form because of Persian and Islamic influences in northern India. The main emphasis in Carnatic music is on vocal music; most compositions are written to be sung, and even when played on instruments, they are meant to be performed in gāyaki (singing) style.

Although there are stylistic differences, the basic elements of śruti (the relative musical pitch), swara (the musical sound of a single note), rāga (the mode or melodic formulæ), and tala (the rhythmic cycles) form the foundation of improvisation and composition in both Carnatic and Hindustani music. Although improvisation plays an important role, Carnatic music is mainly sung through compositions, especially the kriti (or kirtanam) – a form developed between the 14th and 20th centuries by composers such as Purandara Dasa and the Trinity of Carnatic music. Carnatic music is also usually taught and learned through compositions.

Carnatic music is usually performed by a small ensemble of musicians, consisting of a principal performer (usually a vocalist), a melodic accompaniment (usually a violin), a rhythm accompaniment (usually a mridangam), and a tambura, which acts as a drone throughout the performance. Other typical instruments used in performances may include the ghatam, kanjira, morsing, venu flute, veena, and chitraveena. The most outstanding performances, and the greatest concentration of Carnatic musicians, are to be found in the city of Chennai.[3] Various festivals are held throughout India and abroad which mainly consist of Carnatic music performances, such as the Madras Music Season, which has been considered to be one of the world's largest cultural events.[4][5] </p>
      </div>

<div className="iconStyle">     
  <span><SocialIcon url="https://twitter.com/DruthiPolisetty" /> </span>
  <span><SocialIcon url="https://www.facebook.com/Druthi-1445833588863024/" /> </span> 
  <span><SocialIcon url="https://www.youtube.com/channel/UC1K7gTwxjnBHVH699md7Cow?view_as=subscriber" /> </span>
  <span><SocialIcon url="https://www.instagram.com/druthipolisetty/" /> </span>
</div>
</div>
    );
  }
}

export default App;
